on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output3: ${{ steps.step3.outputs.file }}
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"
      - id: step3
        run: echo "file=$(cat $GITHUB_OUTPUT)" >> "$GITHUB_OUTPUT"
      - id: cat-event
        run: cat ${{github.event_path}}
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
          OUTPUT2: ${{needs.job1.outputs.output2}}
          OUTPUT3: ${{needs.job1.outputs.output3}}
        run: echo "$OUTPUT3"
    
